
spring:
  datasource:
    hikari:
#      driver-class-name: com.p6spy.engine.spy.P6SpyDriver
      username: sa
      password:
      jdbc-url: jdbc:h2:~/test
      driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    database: h2
    generate-ddl: false # 시작할 때 스키마를 초기화합니다.
    open-in-view: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show-sql: true
        use_sql_comments: true
        default_batch_fetch_size : 100
  main:
    allow-bean-definition-overriding: true

#      naming-strategy: org.hibernate.cfg.EJB3NamingStrategy
#    properties:
#      hibernate.cache.use_second_level_cache: true
#      hibernate.cache.use_query_cache: false
#      hibernate.generate_statistics: true



logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
  ## file: %d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
  level:
    p6psy: INFO
    root: ERROR
    org.springframework.web: ERROR
    com.project.toyproject : INFO
    org.hibernate    : ERROR
    org.hibernate.SQL: ERROR

